### ISSUE TITLE
Crash upon getCapability() on a furnace (1.12.2-1.4.0-174)

### ISSUE THREAD

**Issue by asiekierka** [CyclopsMC/CommonCapabilities#13]
#### Issue type:

- :bug: Bug

____
#### Short description:

I break a furnace. My fancy event handler executes this line of code:

    Lockable lock = tile.getCapability(Capabilities.LOCKABLE, null);

#### Expected behaviour:

Not crashing.

#### Actual behaviour:

Crashing.

#### Steps to reproduce the problem:

1. Install latest Charset build (lib + storage.locks will do)
2. Break a furnace.
____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-1.4.0-174
- CyclopsCore: Whichever version that version of CommonCapabilities pulls in via Maven, which happens to be 0.10.21-708
- Minecraft: 1.12.2
- Forge: 14.23.1.2589

#### Log file:

This snippet should be sufficient.

```
java.lang.ClassCastException: org.cyclops.commoncapabilities.modcompat.vanilla.capability.recipehandler.VanillaFurnaceRecipeHandler cannot be cast to pl.asie.charset.api.locks.Lockable
	at pl.asie.charset.module.storage.locks.LockEventHandler.getLock(LockEventHandler.java:84)
	at pl.asie.charset.module.storage.locks.LockEventHandler.onLeftClick(LockEventHandler.java:162)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_367_LockEventHandler_onLeftClick_LeftClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1103)
	at net.minecraft.client.multiplayer.PlayerControllerMP.clickBlock(PlayerControllerMP.java:245)
	at net.minecraft.client.Minecraft.clickMouse(Minecraft.java:1628)
	at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2374)
	at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2145)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1933)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1186)
	at net.minecraft.client.Minecraft.run(Minecraft.java:441)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)
```

**Comment by rubensworks** [comment]
Ah, I already know what's going on, will push a new version shortly.

(This problem won't occur in the public release, so no problem there)

**Comment by rubensworks** [comment]
@asiekierka FYI, the (backwards-compatible) maven repo has now been updated to https://oss.jfrog.org/artifactory/simple/libs-release/

New build should appear there once Travis finishes its build.
