### ISSUE TITLE
Logged Warning on Version Check

### ISSUE THREAD

**Issue by Jophire** [CyclopsMC/CommonCapabilities#29]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Logged a warning in minecraft log.

#### Steps to reproduce the problem:

Install mod, launch minecraft.

#### Expected behaviour:

Everything is fine, just a warning in the log.

____

#### Versions:

- This mod: 2.56 --I am all over the place, sorry. Was looking at cyclops cores page.
- Minecraft: 1.16.5
- Forge: 35.0.44

#### Log file:

Looking at the repo, I think its just missing a hyphen.
```
[17:56:11] [Forge Version Check/WARN]: Failed to process update information
java.io.FileNotFoundException: https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/commoncapabilities.json
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884) ~[?:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.8.0_51]
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:171) ~[?:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:187) [?:?]
	at net.minecraftforge.fml.VersionChecker$1$$Lambda$13778/1115415381.accept(Unknown Source) [?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_51]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:139) [?:?]
Caused by: java.io.FileNotFoundException: https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/commoncapabilities.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835) ~[?:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[?:1.8.0_51]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_51]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[?:1.8.0_51]
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:155) ~[?:?]
	... 4 more
```

**Comment by rubensworks** [comment]
Thanks for reporting!
